services:
  devns:
    container_name: devns
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: baginskistudio/devns:latest
    restart: unless-stopped
    network_mode: host
    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    environment:
      PORT: 53
      DEBUG_MODE: "false"
      MAX_WORKERS: 10
      MAX_MESSAGES: 20
      DNS_SERVERS: "1.1.1.1;1.0.0.1;8.8.8.8"
    volumes:
      - ../config:/config:ro
