name: Continuous Integration (CI)
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CITATION.cff"
      - ".github/FUNDING.yml"
      - ".gitignore"
      - "**.md"

  pull_request:
    branches:
      - "main"
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Format Check
        run: cargo fmt --all --check

      - name: Run Tests
        run: cargo test --all
