name: Release Orchestrator
on:
  push:
    tags:
      - "v*"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  linux:
    name: Linux x86_64 MUSL
    uses: ./.github/workflows/linux.yml

  windows:
    name: Windows x86_64 GNU
    uses: ./.github/workflows/windows.yml

  docker:
    needs: [linux]
    uses: ./.github/workflows/docker.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  release:
    needs: [linux, windows]
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    secrets: inherit
