name: Windows x86_64 GNU Build
on:
  workflow_call:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt update && sudo apt install -y mingw-w64
      - run: rustup target add x86_64-pc-windows-gnu
      - run: ./scripts/build.sh --windows --release
      - run: |
          mkdir -p dist/windows
          cp target/x86_64-pc-windows-gnu/release/devns.exe dist/windows/
          cp -r config dist/windows/
          tar -czf dist/devns-windows-x86_64-gnu.tar.gz -C dist/windows .
      - uses: actions/upload-artifact@v4
        with:
          name: linux-musl
          path: dist/devns-windows-x86_64-gnu.tar.gz
